sudo: required

services:
  - docker

script:
  - docker build -f $BUILD_FILE -t $TAG .
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG
  - docker run $TAG

env:
  matrix:
    - BUILD_FILE="Dockerfile"
      TAG="thrift-4042"
    - BUILD_FILE="thrift-from-source.Dockerfile"
      TAG="thrift-4042:thrift-from-source"
    - BUILD_FILE="thrift-from-source-patched.Dockerfile"
      TAG="thrift-4042:thrift-from-source-patched"
