sudo: required

services:
  - docker

script:
  - docker build -t thrift-4042 .
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
  - docker run thrift-4042
